### PR TITLE
Improve instructions for rocker-bogie assemblies, add more pictures

### PR DESCRIPTION
**Pull request by Achllle**

### CODE REVIEW

**Comment by abust005** [comment]
Looks good, just a pair of thoughts:

In the new image ```front_servo_to_rb.png```, there's a drawing that I imagine is intended to show how wiring should be routed, but it seems a little too abstract; I thought it might've been a scribble. 

Also I notice that the servo is facing the wrong way there, which isn't a huge deal, but the ribbon cable strain relief is facing away from the wiring drawing.

**Comment by Achllle** [comment]
Yeah, it's a bit lazy. I think a picture would be much better but I didn't have a good one. 
Good catch on the onshape model. I'll have to flip it, I hadn't noticed that.

**Comment by Achllle** [comment]
@abust005 Addressed your comment. Let me know if you think something else could be improved!

**Comment by abust005** [comment]
Looks pretty good to me! I'll sign off on this one

**Review by ericjunkins — COMMENTED** [review]
My feedback would be that the pictures look great and more descriptive. As I didn't build the V2 version of your rocker bogie I don't know if i'm fully qualified to say it addressed the issues that necessitated the PR though.

**Comment by apollokit** [comment]
> My feedback would be that the pictures look great and more descriptive. As I didn't build the V2 version of your rocker bogie I don't know if i'm fully qualified to say it addressed the issues that necessitated the PR though.

Agree, looks good, but I haven't built this version yet

**Comment by Achllle** [comment]
Ok, I'll merge this in because it's better than what was there before and we can improve it as comments come in. Thanks for the feedback everyone!

**Pull request merged**
