### PR TITLE
A few updates to electrical docs based on assembly experience

### PR DESCRIPTION
**Pull request by apollokit**
Based on my assembly experience. Note that I can't get the pdf docs to build with all the images present, for some reason. Those ought to be updated before this PR gets approved.

Updates:
- clarified in PCB assembly doc that roboclaw windows driver needs to be installed
- explicitly stated that the polarity of red/black wires doesn’t matter for the corner motors
- electrical build section 3, the E29 cable isn’t used - removed that
part from the table

### CODE REVIEW

**Comment by Achllle** [comment]
I've been using a combination of overleaf.com and MiKTeX to generate the PDFs. I can generate them for you, but that's not a very sustainable model I would argue 😅  Otherwise this LGTM

**Comment by apollokit** [comment]
All the images get included successfully when you do it that way?

**Comment by Achllle** [comment]
yes, master should compile without changes. Is it not including some images or all? MiKTeX or Overleaf? For Overleaf I couldn't figure out a way to upload the entire folder structure so I had to manually arrange files and folders in the right way. That's why I use MiKTeX by default

**Comment by apollokit** [comment]
Ok, finally got this done. I had to go fix a bunch of file extensions... we should be aware of case-sensitivity for filenames on unix systems, and only use e.g. ".png" instead of both ".png" and ".PNG".

The pdfs are good now, all images got included. @ericjunkins , look good?

**Pull request merged**
