### PR TITLE
USAi Labs AUDACITY

### PR DESCRIPTION
**Pull request by JHPHELAN**
without videos

### CODE REVIEW

**Comment by Achllle** [comment]
Awesome, looks great, @JHPHELAN ! Only thing is that the pull request contains two videos of almost 100MB which makes cloning the repo slow. You can drag and drop a video so it's hosted on Github's servers rather than include it in the source code. To do that, navigate to the file in your branch ([link](https://github.com/JHPHELAN/open-source-rover/blob/USAi_Labs_AUDACITY/examples/builders_gallery.md), select the pencil button on the top right to edit the file, then drag and drop the video in place. I'd only add one so we can have many builds without the page loading slowly.

Since you have 4 images, you can display those in a 2x2 grid using the table rather than a 4x1 like you have now, but I can help with that if you don't know how.

**Comment by JHPHELAN** [comment]
@Achllle Following examples moved images to 2x2 and made link to Youtube as video was too large to drop.  Preview looks ok, hope it translates.

**Comment by Achllle** [comment]
I removed the video files and did some formatting on the table. I also created a thumbnail for the youtube video rather than just displaying the link. I'll merge this in, if you want to make additions, you're welcome to make another PR!

**Comment by JHPHELAN** [comment]
Thanks for the clean-up!  Looks good.

**Pull request merged**
