### PR TITLE
Make part lists csv files. Build master part list from sub assemblies

### PR DESCRIPTION
**Pull request by xtream1101**
Started to make the parts list into csv files. The master list gets built off of the sub assemblies list. That way only one list needs to get updated as assemblies change/update.

TODO:
- [x] Read part counts from latex build docs
- [x] Add Links to parts reference csv
- [x] Confirm part counts are correct in the sub assemblies
- [x] Remove old xlsx files

### CODE REVIEW

**Comment by vssystemluba** [comment]
I very much like the idea of automatically building the master parts list.

HOWEVER: I will caution that you will need to be intelligent about dealing with common parts like nuts, bolts, screws, standoffs, fasteners, etc that are ordered in large packs. The parts list for some of the subassemblies include, for instance, a pack of 100 where the subassembly itself only needs 4.

Simply adding all the quantities of all the subassemblies will result in too many packs of these items in the master parts list.

**Comment by xtream1101** [comment]
@vssystemluba From what I have seen so far, the counts that are listed in the sub assemblies is the actual count used and not the packs needed.
But I do agree that caution needs to be taken. Also for things like wire and loctite, its hard to know exactly how much is needed and the amount may have to be set in the master list.

**Comment by xtream1101** [comment]
@0x48piraj I am, was on hold for a bit while I updated the pdf's to use a latex table for the parts list.

**Comment by Roman545** [comment]
Колеса должны быть по объемнее и табло по шире немножко

**Comment by xtream1101** [comment]
Ok, I think this is at a good state. Let me know what you all think.

**Comment by ericjunkins** [comment]
Hey so after thinking about the way to sort through this the best I think it might be a better idea to do your match from the part reference on the reference designator instead. I think it's less likely to have typos, for instance we saw a typo in the name of one of the screws that says "buttonheadScrew".

I think this leads to thinking about trying to add reference designators to all components, but for now maybe just if there is no ref des default to qty of (1) unless there is an override from the parts reference csv.

Let me know your thoughts on those, overall I like the way this was done to pull qts from the build docs directly, so only managing the build docs is necessary

**Comment by 895aungye** [comment]
Duplicate of #37

**Comment by 895aungye** [comment]
> 

- [ ] #36 @Roman545

**Comment by vssystemluba** [comment]
@xtream1101 are you still working this?  We have a few parts-list-related issues that we'd like to resolve quickly and we'd prefer to have it all fixed and dynamic all in one branch.

If you're not working on it that's fine; just let us know and we can finish out this pull request on our end.

**Comment by xtream1101** [comment]
@vssystemluba Sorry about the delay with this. I will make the changes this evening and make sure this can get merged in asap.

**Comment by xtream1101** [comment]
@ericjunkins It currently does match on the part reference and not the name, that was a typo from the `parts_list_reference.csv` which is the source of truth of the part name and any overrides. I did it that way since there is a higher chance of a typo in the build docs since it may be used a few places.

As for the parts not in the reference csv but in the build docs, I will default the counts to 1 and add at the bottom of the master list, as well as warn the user they are not in the reference sheet.

The only parts that do not have a reference number currently are the wires and such that were not in the mechanical sections but I added to the reference sheet for now so they still show in the master list. But it would be great for everything to have a number in the future.

I will add docs and make sure this is up to date with the master branch.
Let me know if there is anything else and I will work on it asap. Again, sorry for the delay.

**Comment by ericjunkins** [comment]
@xtream1101 thanks for doing that and the clarification, we will need a bit of time to look all it over and make sure it looks good, but hopefully at that point we can also go and clear up some of these other part qty inconsistencies that are open issues as well.

**Comment by vssystemluba** [comment]
I am going to take a look at merging this over the next couple weeks.

In addition to the above and what's already been mentioned in other issues, @jmolaro reached out to me on the forum and gave me a few additional notes about parts inconsistencies; we'll want to make sure each of these are addressed:


#6-32 x   1/4 Button head Screw | McMaster | B1 | 92949A144 |   | description,   part, picture in doc match
-- | -- | -- | -- | -- | --
#6-32 x 3/8 Button head Screw | McMaster | B2 | 92949A146 |   | description, part,   picture in doc match
#6-32 x 1/2 Button head Screw | McMaster | B3 | 92196A148 |   | part ref is socket   head screw, same length and thread
#6-32 x 5/8 Button head Screw | McMaster | B4 | 92196A150 |   | part ref is socket   head screw, same length and thread
#6-32 x 3/4 Button head Screw | McMaster | B5 | 92196A151 |   | part ref is socket   head screw, same length and thread
#6-32 x 1.0 Button head Screw | McMaster | B6 | 96006A252 |   | DOES NOT   MATCH-ordered 92196A165 instead, same as ref but stainless steel. Socket head   fully threaded, same length as in doc.
#6-32 x 1.25 Button headScrew | McMaster | B7 | 92949A160 |   | part ref is socket   head screw, same length and thread
#4-40 x 1/4 Button head Screw | McMaster | B8 | 92949A106 |   | description, part,   picture in doc match
#4-40 x 1.25 Button head Screw | McMaster | B9 | 92196A032 |   | DOES NOT MATCH- doc   shows partially threaded button, part ref to fully threaded socket. Ordered   92196A302, partially threaded socket, same length
M2.5 x 4mm Screw | McMaster | B10 | 91292A015 |   | discrepancy w/ length   in doc, think 4mm is correct
#6-32 Locknuts | McMaster | B11 | 90631A007 |   | description, part,   picture in doc match
#4-40 Locknuts | McMaster | B12 | 90631A005 |   | description, part,   picture in doc match
#2-56 x 3/16 Button head Screws | McMaster | B13 | 91255A077 |   | DOES NOT MATCH- part   ref 1/4" screws. Ordered 91255A076, same part but 3/16"

**Comment by vssystemluba** [comment]
Consolidating and summarizing information from other issues here:

As described in #39, the screws B10 should be https://www.mcmaster.com/92095a458
As mentioned in #40, the screws B13 should be https://www.mcmaster.com/91255A076

As mentioned in #42, we need to remove any parts with duplicate refs (currently an issue with E20, and E23)

**Comment by vssystemluba** [comment]
WOOHOO!!!!  Thanks to everyone who contributed on this big rewrite.  It's finally stable!  You can now generate the master parts list by running `python3 build_parts_list.py`.

The above merge resolves #30, #39, #40, and #42.

**Pull request merged**
