### PR TITLE
Adding a bash script for formatting/auto numbering a README file

### PR DESCRIPTION
**Pull request by apollokit**
auto numbers headings in readme files

`$ format_readme.sh path/to/README.md`

### CODE REVIEW

**Review by Achllle — COMMENTED** [review]
I'm not a huge fan of having folks run bash scripts to format readmes. It increases the barrier for contributing, it needs to be documented clearly, and can have bugs.

It's much easier to either ask people to autonumber or not have numbering at all.

**Comment by apollokit** [comment]
It's just a script that does something useful for people who know how to use it. It's stashed out of the way in a directory. Hardly seems like a problem.

Might be good to add a WARNING line in the header saying only power users should use it.

Otherwise, I think this is good to add.

**Comment by apollokit** [comment]
@ericjunkins tiebreaker?

**Comment by ericjunkins** [comment]
👎

**Pull request closed without merging**
