### PR TITLE
Added Australian Catalog and Pricing

### PR DESCRIPTION
**Pull request by au-chrismor**
this is a simple update as a courtesy to Australia/New Zealand Builders.  I have included localised vendors for the electronic components and assemblies.

### CODE REVIEW

**Comment by ericjunkins** [comment]
I think what's best is to have a different branch for this instead. I like the idea but I feel like if we do this for one country outside the US then we have to support adding any /all, and it feels like that is going to make the parts list unmanageable

**Comment by vssystemluba** [comment]
thanks @au-chrismor for putting this together!  This will be a huge help to our friends in Australia and New Zealand!

I also have a bit of heartache with this particular pull request, but only because our current parts list is auto-generated from the build docs and we'd want to follow that same pattern with international parts lists.

I think the best way to proceed is to add a folder in the already existing `parts_list/` folder for international builds.  That way, as we push forward and continue to make updates to the project, the international parts lists will not get lost in a deprecated branch that possibly hasn't been updated.

@au-chrismor, I suggest that you review the README document in the `parts_list/` folder of our repository at https://github.com/nasa-jpl/open-source-rover/tree/master/parts_list.  That folder contains information about how our parts lists are auto-generated from our build documents.  I think that you should be able to add a new folder (`international/` or similar) and add your own custom version of the `parts_list_reference.csv` file, so that we can automatically re-build the international parts lists as we move forward and make other changes to the project.

Let us know if you have any questions or concerns.  Thanks again for making this addition to the project!

**Comment by au-chrismor** [comment]
Ok,I will create a branch for international components as presented.  Perhaps others will chime in further down the line.  I realized immediately upon generating the request that I  didn't check the build process, so apologies for that.If someone with rights can kill my merge request. That would be great.Thanks,Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: "Mik (Michael) Cox" <notifications@github.com> Date: 11/5/19  03:06  (GMT+10:00) To: nasa-jpl/open-source-rover <open-source-rover@noreply.github.com> Cc: Chris Moran <chris.moran@emergent.com.au>, Mention <mention@noreply.github.com> Subject: Re: [nasa-jpl/open-source-rover] Added Australian Catalog and Pricing (#112) thanks @au-chrismor for putting this together!  This will be a huge help to our friends in Australia and New Zealand!
I also have a bit of heartache with this particular pull request, but only because our current parts list is auto-generated from the build docs and we'd want to follow that same pattern with international parts lists.
I think the best way to proceed is to add a folder in the already existing parts_list/ folder for international builds.  That way, as we push forward and continue to make updates to the project, the international parts lists will not get lost in a deprecated branch that possibly hasn't been updated.
@au-chrismor, I suggest that you review the README document in the parts_list/ folder of our repository at https://github.com/nasa-jpl/open-source-rover/tree/master/parts_list.  That folder contains information about how our parts lists are auto-generated from our build documents.  I think that you should be able to add a new folder (international/ or similar) and add your own custom version of the parts_list_reference.csv file, so that we can automatically re-build the international parts lists as we move forward and make other changes to the project.
Let us know if you have any questions or concerns.  Thanks again for making this addition to the project!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nasa-jpl/open-source-rover/pull/112#issuecomment-491361245",
"url": "https://github.com/nasa-jpl/open-source-rover/pull/112#issuecomment-491361245",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by au-chrismor** [comment]
Backing out of this merge after discussions.  Will revisit later

**Comment by vssystemluba** [comment]
@au-chrismor: When you do this, please create a folder within the same master branch rather than creating an entirely new branch dedicated to international builds.

The flow should probably be:

- Create a new international/ folder within the existing parts_list/ folder
- Create a folder for Australia / New Zealand
- Duplicate the existing `parts_list_reference.csv` into the Australia / New Zealand folder and make the necessary changes to modify the vendors and links for our Australia / New Zealand friends
- Modify the `parts_list/build.py` script to also search into each subdirectory of the international/ folder and generate a version of the master parts list for that country

Let us know if you have any questions on this or need assistance.  It'll be a great feature; thanks for bringing it up and considering contributing!!

**Comment by MohamedKhlil** [comment]
guys what do you think about AI controlling the rover it’s will be more easy after sending him to mars and taking by himself all the data

for all how thing about it’s groupe will be also created in WhatsApp just text this number with your name and you degree thanks number is 0022234540455

On May 11, 2019, at 4:38 PM, Mik (Michael) Cox <notifications@github.com<mailto:notifications@github.com>> wrote:


@au-chrismor<https://github.com/au-chrismor>: When you do this, please create a folder within the same master branch rather than creating an entirely new branch dedicated to international builds.

The flow should probably be:

  *   Create a new international/ folder within the existing parts_list/ folder
  *   Create a folder for Australia / New Zealand
  *   Duplicate the existing parts_list_reference.csv into the Australia / New Zealand folder and make the necessary changes to modify the vendors and links for our Australia / New Zealand friends
  *   Modify the parts_list/build.py script to also search into each subdirectory of the international/ folder and generate a version of the master parts list for that country

Let us know if you have any questions on this or need assistance. It'll be a great feature; thanks for bringing it up and considering contributing!!

**Comment by au-chrismor** [comment]
Hi All,

I've followed those recommendations, and I agree, it's a much better way.
Hopefully now others can share their local information.

Thanks for all the feedback.

**Pull request closed without merging**
