### PR TITLE
Fixed silkscreen for J18

### PR DESCRIPTION
**Pull request by abust005**
Silkscreen for J18 (RC3 Motor Supply) was inconsistent with the net going to those pins

### CODE REVIEW

**Comment by ericjunkins** [comment]
Can I ask what the scope of this MR is? The title is fixing silk screen and has a commit for that which @apollokit was to review (I think he was out of town, maybe still is). But now I see the WireViz diagrams being added too. I think it would be cleaner to keep those for a separate MR and to do just the silkscreen update here.

**Comment by ericjunkins** [comment]
I'm happy to do the review of the silkscreen instead and could do that soon to get this MR in though

**Comment by abust005** [comment]
Thank you for bringing this to my attention, the WireViz diagrams should not have ended up in this MR.

**Comment by ericjunkins** [comment]
oh, these changes are made with a newer version of KiCAD than we were previously using. I think in general I have opposition to upgrading KiCAD version. @abust005 you didn't have any import issues in moving forward in version?

**Comment by abust005** [comment]
@ericjunkins I did notice it was a newer version because KiCAD told me, but I was unsure as to what the version currently in use is. 

As far as import issues, I'm not aware of any; I didn't run the DRC on anything, but I was able to get the boards fabbed with no issues

**Comment by ericjunkins** [comment]
We noticed we were a bit behind on KiCAD versions when we started designing this rev but decided not to upgrade in case we had compatibility issues. But It seems if there isn't an issue then I see no reason not to.

**Comment by abust005** [comment]
I'm far from an expert on the matter, so I can't speak very much to any compatibility issues or lack thereof, I can only offer my own anecdotal experience :)

**Comment by ericjunkins** [comment]
Looks good to me, here's a quick screencap for everyone else of the component in question and the silkscreen corrected. 
image

I have another request looking at this, can you increment the silkscreen pcb version as well? This would be v2.0.3 and has a silkscreen label on both of the boards that need updated.

**Comment by abust005** [comment]
Updated version silkscreen per request

**Review by ericjunkins — APPROVED** [review]
Approved!

**Comment by Achllle** [comment]
@sethfischer Noticing that the readthedocs build is failing due to 

```
Problem in your project's configuration. No default configuration file found at repository's root.
```

I will merge this in since it's entirely unrelated, but wanted to check if you knew what may be causing this.

**Comment by ericjunkins** [comment]
Thanks for the fix @abust005 !

**Comment by sethfischer** [comment]
> @sethfischer Noticing that the readthedocs build is failing due to
> 
> ```
> Problem in your project's configuration. No default configuration file found at repository's root.
> ```

Read the Docs failed to build this branch because the branch was created off master before #430 was merged.

A `git fetch upstream` and `git rebase upstream master` would have allowed the docs to build for this branch.

**Pull request merged**
