### PR TITLE
Update readme to add BOM and part references for control board assembly

### PR DESCRIPTION
**Pull request by apollokit**
Finally add the proper documentation for control board part references to the repo.

Also fixed a couple small todos in the readme file for the pcb - reviewed section numbering and linked to the schematics/layout files

### CODE REVIEW

**Review by ericjunkins — COMMENTED** [review]
The BOM and instructions at a glance look good to me. I didn't look through all the line items and BOM stuff to make sure it all lines up with what is needed though. Do you feel confident about that?

**Comment by apollokit** [comment]
> The BOM and instructions at a glance look good to me. I didn't look through all the line items and BOM stuff to make sure it all lines up with what is needed though. Do you feel confident about that?

I think there's a little iteration to do there, admittedly. The standoffs are the biggest thing. I figured it would be good to get these files in and versioned, at least, and follow up to make sure everything is as up to date as it should be. Maybe not the best process.

**Comment by Achllle** [comment]
This is a classic case of balancing speed of getting improvements in vs making sure that getting a half solution in doesn't just stay a half solution.

@apollokit it's up to you to decide if it will be best if we get this in now and you make a follow-up PR soon :tm: (<6 weeks) with improvements or you add in the final pieces in a shorter timeline (<2 weeks) and we merge it in and that's it.

**Comment by apollokit** [comment]
Went ahead and merged. I went through the line items again and I'm pretty confident things are mostly right. There could be some small mistakes in there, but nothing that should be a blocker.

More work to follow up on the TODOs here: https://github.com/nasa-jpl/open-source-rover/pull/449

**Pull request merged**
