### PR TITLE
Minor word change for clarification in electrical

### PR DESCRIPTION
**Pull request by SConaway**
Might be more clear for those unfamiliar with this project

### CODE REVIEW

**Review by apollokit — APPROVED** [review]
Indeed! Good suggestion.

**Comment by apollokit** [comment]
Feel free to merge @SConaway , cuz that's the way we do things around here apparently

**Comment by SConaway** [comment]
@apollokit, thanks for the approval. I don’t have write access to commit directly to this repo or merge PRs.

**Comment by apollokit** [comment]
ah, right.

**Pull request merged**
