### PR TITLE
Fix all the paths + example README.

### PR DESCRIPTION
**Pull request by apollokit**
done:
- created example read me
- renamed all directories to be lowercase and with underscores

still todo:
- move all images to a root folder @ericjunkins 
- rename all images to have lowercase extensions @ericjunkins
- change jpgs to pngs @ericjunkins

### CODE REVIEW

**Comment by apollokit** [comment]
So I actually just decided to toss renaming all image extensions over to you @ericjunkins , to more efficiently batch this work. Hopefully that's all right.

All, feel free to propose changes to the example read me

**Comment by dcschooley** [comment]
This is the most awesome PR I’ve ever seen.

**Comment by apollokit** [comment]
> This is the most awesome PR I’ve ever seen.

Definitely wins at number of files.

**Comment by apollokit** [comment]
We also need to fix the wheel readme with this PR, because it's currently broken @Achllle

**Comment by apollokit** [comment]
okay, @Achllle , images are ready to go now. Feel free to fix the wheel assembly document, and we'll call it a day with this PR

**Comment by ericjunkins** [comment]
@apollokit  @Achllle do we have outstanding stuff to do on this still?

**Comment by Achllle** [comment]
@apollokit Did you go through whatever else is broken because of this overhaul?
This really should have been done in chunks - renaming and moving files is easy, updating the documentation and tracking down what has changed is not. The diff is so large that GitHub can't even load the page.

**Comment by apollokit** [comment]
No, I didn't go through other stuff that was broken. The plan we came up with was to move all the files on this PR, and fix things for individual READMEs in other PRs.

We could have done it in chunks, yes. But I doubt that would have been much easier, and probably would have gotten more complicated with organizing all the files that got moved on individual PRs. We chose this way, for better or worse, so might as well just get on with it.

**Comment by apollokit** [comment]
I'll finish this up tonight

**Comment by apollokit** [comment]
Okay, got this mostly done - images fixed. Just need to fix formatting.

**Comment by apollokit** [comment]
force pushed the hell out of it ^

okay, I think this is done now, wheel assembly read me is updated. Also had to update the example readme cuz it looked a little bad in some spots.

as soon as I can get somebody to check my work, we can close this out.

**Comment by ericjunkins** [comment]
@apollokit What all did you need reviewed for this? There are quite a few things to look at in the PR haha. Things I looked over:
- File/folder names being renamed properly 
- Images moved to the new location at /images/.....
- Image conversion to .png format
- Wheel assembly README verified to be fixed and working

Looking at the template I think it's maybe missing a few things about organization and examples, what do you think about the following? 

---
Items to change for each specific README are marked by `red highlighted text`

#  `Template Assembly Name`

Wheels picture
` Example Final result picture`

## 1. Features

* `Feature 1`
* `Feature 2`
....

## 2. Information about module 

### 2.1 Skills

* `Required Skill 1`
* `Required Skill 2`

### 2.2 Tools

* `Required tool 1`
* `Required tool 2`
...

### 2.3 Dependencies on Other Modules

* `Dependency 1`
....

### 2.4 Mechanical Interface/Attachments to Rover

* `Mechanical Interface 1 (include part and assembly)` 
* `Mechanical interface 2 `
...

## 3. Machining/Fabrication

`template for table organization`
| item                              | ref | qty |                                                                 img |
| --------------------------------- | --- | --- | ------------------------------------------------------------------: |
| item 1                            | ref1 | qty1   |  |
| item 2         | ref2  |  qty2   |        |

> `Indented text to highlight note about`

|   |
|:-:|
| Sample side-by-side figure |

## 4. Assembly

### 4.1 `Assembly Subsection 1`

`Insert parts list for subsection here`

#### 4.1.1 `Subsubsection, for individual step 1`

#### 4.1.2 `Subsubsection, for individual step 2`

### 4.2 `Assembly Subsection 2`

`Insert parts list for subsection here`

#### 4.2.2 `Subsecsection, for individual step 1`

**Comment by Achllle** [comment]
Since I can't even look at the diff of a single commit, I started randomly inspecting pages on your branch. Noticed a few broken links:

* missing images on [mechanical overview page](https://github.com/apollokit/open-source-rover/tree/readme_foundation_pouring/mechanical)
* missing image on [mechanical integration readme](https://github.com/apollokit/open-source-rover/tree/readme_foundation_pouring/mechanical/mechanical_integration)
* missing image on [main body](https://github.com/apollokit/open-source-rover/tree/readme_foundation_pouring/mechanical/body_assembly)
* missing image on [corner steering readme](https://github.com/apollokit/open-source-rover/tree/readme_foundation_pouring/mechanical/body_assembly)

I'll stop here, it seems like each of the readmes have a broken image.

**Comment by apollokit** [comment]
@ericjunkins 

Wait....to be clear, are you suggesting we take content out of the example read me and just have placeholder headers like you wrote above? or are there specific structural points you want changed? I guess i'm just not clear what you mean to say with the content after "the following"

@Achllle yeah. The idea with this PR was to fix the example read me and the wheel assembly readme, and fix the rest on other PRs.

**Comment by Achllle** [comment]
To avoid having a broken master, I think it's best to fix at least the ones we know to be broken here.

**Comment by ericjunkins** [comment]
@apollokit sorry for maybe not being clear, I'm suggesting verbatim what I have posted underneath it. If you're following a template from online I usually like when it tells me what I should be changing and where, so having a list of what it would look like, and you just fill in the content with the placeholders it has is what i'm suggesting. This was to remove confusion of how it should be using all the potential content

**Comment by apollokit** [comment]
@ericjunkins honestly I'd rather skip it. I think it's pretty clear from the example doc. Just kinda seems like makework at this point. Totally cool if you want to do it though.

@Achllle fair enough, I hadn't really thought about breaking master. Though how's about we just target a temporary branch with this PR (say, "docs_update"), instead of master. That way we _can_ finished this PR out and have people work off of that branch.

**Comment by Achllle** [comment]
I'm not entirely sure how that helps. Perhaps the easiest thing to do is to list all the things that need to be checked/fixed and assign them? If it's just the above, happy to do those

**Comment by apollokit** [comment]
@Achllle we end up staging all the changes so that we don't have to continue dangling work on this massive commit, and we avoid leaving master in a semi updated state. Seems like that'd help the momentum. It's not hard to just push to a single staging branch.

though sure, if you want to start updating all those things on this commit go for it

**Pull request merged**
