### PR TITLE
Modified README.MD, added tables

### PR DESCRIPTION
**Pull request by 0x48piraj**
* Made tables for Cart Share
* clarified the following note :
_"Note: JPL and Caltech have no official affiliation with this forum; it is run by individuals of the general public."_

Ping @ericjunkins

### CODE REVIEW

**Comment by ericjunkins** [comment]
I do think the tables aesthetically look better horizontally organized

**Comment by 0x48piraj** [comment]
Thanks a lot, it was my first pull request. I was feeling nervous.

I am reading and learning this project for last ~10 days and will try my level best to make some positive contributions :)

**Comment by ericjunkins** [comment]
Great to hear, let us know if you are looking for anything in particular to do and we could work together to try and find something

**Comment by 0x48piraj** [comment]
Thanks a lot, I definitely will come up with some things I am tinkering on. I will love to work with the Open Source Rover team.

**Pull request merged**
