### PR TITLE
Head readme

### PR DESCRIPTION
**Pull request by ericjunkins**
Moving head assembly instructions to README based instructions instead.

### CODE REVIEW

**Comment by ericjunkins** [comment]
Closes #217

**Comment by Achllle** [comment]
^ that only works when it's in the original description or in commits.

**Comment by apollokit** [comment]
Needs update based on https://github.com/nasa-jpl/open-source-rover/pull/232

**Comment by ericjunkins** [comment]
Closing to use #247 PR instead

**Pull request closed without merging**
