### PR TITLE
Swap out wheels to wasteland wheels

### PR DESCRIPTION
**Pull request by Achllle**
It's a fairly big increase in price but they are simpler to attach, require one less seller, and are much bigger (=faster).

Two other options are specified as alternatives.

- [ ] update the build instructions to match new wheels

### CODE REVIEW

**Comment by Achllle** [comment]
decision is to switch to smaller Gobilda wasteland wheels as the default

**Comment by murphcj** [comment]
I just drilled the holes in the old wheels and there is really no good surface to locate a hole to center the mount pattern with respect to the axis.

If I had a milling machine I could mill a flat or drop a 4mm end mill through, but I don't. Now my wheels wobble since they aren't centered well. 

Bottom line: if I had seen these wheels up front and known the holes are pre-drilled I would have bought the wasteland ones even though they are more expensive.

**Comment by Achllle** [comment]
@murphcj you're right, apologies for letting this sit here for that long. We were debating between the smaller and larger wasteland wheels. I updated the PR to include the smaller wasteland wheels by default and will merge those in now.

**Comment by Achllle** [comment]
Regarding the centering: I remember a community member had made a 3D printable jig in the past to allow for easy drilling. It should be possible to just re-drill holes so they're centered better.

**Comment by murphcj** [comment]
No problem. Really convenient that these wheels are out now. I made a nice little jig out of one of the extra couplings that seemed to get decent results. I had nearly as good luck eyeballing the holes to be honest. 

I realize it's already decided, but another vote in favor is that the seating surface for the heads of the screws in the outside isn't good. 

I think this is a good decision!

**Comment by Achllle** [comment]
The only thing that's left is updating the documentation because that's still pointing to the drilling instructions for the old wheels. Let me know if you'd like to take a stab at creating (simpler) instructions for the newer wheels, otherwise I will get to this over the next few weeks

**Comment by murphcj** [comment]
I'll give it a try. Could be a good intro to git for me.

**Pull request merged**
